// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wudvvkgzinvvbexwdtoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZHZ2a2d6aW52dmJleHdkdG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0Njc4NDUsImV4cCI6MjA3MjA0Mzg0NX0.tFM9-slMHcVtoUCSoqv6mfftrbw_NmJwFY2CvbTbyXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});